export const technologyTags = [
    'React',
    'React Native',
    'Node.js',
    'Express.js',
    'MongoDB',
    'PostgreSQL',
    'MySQL',
    'AWS',
    'Heroku',
    'Firebase',
    'Git',
    'GitHub',
    'GitLab',
    'HTML',
    'CSS',
    'JavaScript',
    'TypeScript',
    'Python',
    'Java',
    'C',
    'C++',
    'C#',
    'PHP',
    'Swift',
    'Kotlin',
    'Ruby',
    'Go',
    'R',
    'Scala',
    'Dart',
    'Rust',
    'Perl',
    'Haskell',
    'Lua',
    'Julia',
    'Elixir',
    'Clojure',
    'Assembly',
    'MATLAB',
    'VBA',
    'Objective-C',
    'Groovy',
    'Visual Basic',
    'PowerShell',
    'CoffeeScript',
    'VB.NET',
    'F#',
    'Scheme',
    'React.js',
    'AngularJS',
    'Vue.js',
    'Ember.js',
    'Backbone.js',
    'jQuery',
    'Django',
    'Flask',
    'Laravel',
    'Ruby on Rails',
    'ASP.NET',
    'Spring',
    'Express',
    'CakePHP',
    'Symfony',
    'CodeIgniter',
    'Phalcon',
    'Zend',
    'Yii',
    'Meteor',
    'Koa',
    'Sails.js',
    'Phoenix',
    'Feathers',
    'AdonisJs',
    'NestJS',
    'Next.js',
    'Nuxt.js',
    'Gatsby',
    'Gridsome',
    'Quasar',
    'Ionic',
    'Flutter',
    'NativeScript',
    'React Native',
    'Xamarin',
    'Electron',
    'NW.js',
    'Jest',
    'Mocha',
    'Enzyme',
    'Chai',
    'Cypress',
    'Puppeteer',
    'Karma',
    'AVA',
    'Jasmine',
    'Protractor',
    'Sinon',
    'Supertest',
    'Nock',
    'Tap',
    'Web Design',
    'Web Development',
    'Mobile Development',
    'Game Development',
    'Software Testing',
    'Software Engineering',
    'Development Tools',
    'E-Commerce Development',
    'Business',
    'Finance',
    'Entrepreneurship',
    'Communications',
    'Management',
    'Sales',
    'Strategy',
    'Operations',
    'Project Management',
    'Business Law',
    'Data & Analytics',
    'Home Business',
    // 'Human Resources',
    // 'Industry',
    // 'Media',
    // 'Real Estate',
    // 'Other Business',
    // 'IT Certification',


    // web 3 tags
    'Solidity',
    'Ethereum',
    'Blockchain',
    'Bitcoin',
    'Web3.js',
    'Truffle',
    'Ganache',
    'Hardhat',
    'Ethers.js',
    'Metamask',
    'OpenZeppelin',
    'IPFS',
    'Infura',
    'Alchemy',
    'The Graph',
    'Chainlink',
    'Uniswap',
    'Aave',
    'Compound',
    'MakerDAO',
    'Synthetix',
    'SushiSwap',
    'Balancer',
    'Yearn Finance',
    '1inch',
    'Curve',
    'Ren',

    // data science tags
    'Data Analysis',
    'Data Visualization',
    'Machine Learning',
    'Deep Learning',
    'Data Science',
    // 'Python',
    // 'R',
    'TensorFlow',
    'Neural Networks',
    'Natural Language Processing',
    'Artificial Intelligence',
    'Computer Vision',
    'Data Analysis',
    'Big Data',
    'Statistics',
    'Probability',
    'SQL',
    'Tableau',
    'Business Analysis',
    'Data Modeling',
    'Pandas',
    'NumPy',
    'Data Mining',
    'Algorithms',
    'Data Engineering',
    'Matplotlib',
    'Data Management',
    'Excel',
    'Power BI',
    'Regression Analysis',
    'AWS Certification',
    'Microsoft Power BI',
    'IBM Data Science',
    'Google Data Analytics',
    'TensorFlow Developer',
    // 'Python for Everybody',
    'Automation',


    

    'Data Structures',
    'Algorithms',
    'Computer Science',
    'Computer Programming',
    'Programming Languages',
    'Software Engineering',
    'Software Testing',
    'Software Development',
    'Web Development',
    'Mobile Development',
    'Game Development',
    'Databases',
    'Data Science',
    'Machine Learning',
    'Cyber Security',
    'Cloud Computing',
    'DevOps',
    'Blockchain',
    'Ethical Hacking',
    'Command Line',
    'Linux',
    'Operating Systems',
    'System Administration',
    'Shell Scripting',
    'Computer Networking',
    'Computer Security',


    // special tags

    'Template',
    'Freelance',
    'Build In Public',
    'Long Term',
    'Community',
    'Open Source',
    'Beginner Friendly',
    'Junior Friendly',
    'Senior Friendly',
    'Remote Friendly',
    'Remote Only',
    'Remote First',
    'Remote OK',
    'Remote Work',
    'Remote Work Only',
    'No Code',

    'Remote',



    'Full Time',
    'Part Time',
    'Contract',
    'Internship',
    'Entry Level',
    'Mid Level',
    'Senior Level',
    'Junior',
    'Senior',
    'Frontend',
    'Backend',
    'Fullstack',
    'DevOps',
    'Product Manager',
    'Designer',
    'Marketing',
    'Sales',
    'Customer Support',
    'Human Resources',
    'Finance',
    'Legal',
    'Business Development',
    'Operations',
    'Engineering',
    'Data Science',
    'Data Analyst',
    'Data Engineer',
    'Data Scientist',
    'Machine Learning Engineer',
    'Software Engineer',
    'Software Developer',
    'Software Architect',
    'Software Tester',
    'Software Quality Assurance',
    'Software Development Manager',
    'Software Development Engineer',
    'Software Development Engineer in Test',




];